version: '2'
services:
    keycloak:
      image: danielpetisme/jhipster-keycloak:latest
#      volumes:
#        - ./import:/opt/jboss/keycloak/import
      environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
      ports:
        - 9080:8080
        - 8443:8443
        - 9990:9990